### ISSUE TITLE
Range not working as intended.

### ISSUE THREAD

**Issue by rcarm98** [hectarek/Random-pitch-generator#1]
- Upper boundary for range will not set as intended.  It seems that when any note in a certain octave is selected, the application still allows higher notes within that octave to play.  For instance, if pitch D4 is selected, the app still allows pitches within the 4th octave to play even if higher than D4 (ie. B4, D#4 etc.)  

- The application also does not allow certain combinations of lower and upper boundary's to be set, even if they are in the correct order of low to high, for instance, the app does not seem to allow a C3 as the lower boundary and B3 as the upper boundary.  This is also true for other combinations.  G#3 and B3 will not work together (although Ab3 and B3 will work which is weird cause G#3 and Ab3 are enharmonic)

(as a small note, we should probably remove any instances of separate enharmonics that could be selected and probably just put them in the same box next to each other)

- All pitches within the app are off by one octave.  Pitches that appear on screen when the tones change are one octave lower than the sounding pitches.  I believe this is also the case for the selected range (If C3 is set as the lower boundary, the sounding tones never actually go lower than a C4)  The pitches in the upper range boundary go more than an octave higher than selected but that has to do with the first issue noted.

If you want to talk about any of these over voice chat some time just let me know!

-Robert

**Comment by hectarek** [comment]
This has been addressed by fixes in the last version. Please open another issue if this still persists
