### ISSUE TITLE
Range Order Incorrect

### ISSUE THREAD

**Issue by HouseOfBLus** [hectarek/Random-pitch-generator#2]
Location: https://github.com/hectarek/Random-pitch-generator/blob/main/src/script/range.js

Error: Note order in range is incorrect
    Range starts on A0, but it should start on C0
        B to C is where octave switches happpen, not G# to A
    This is causing some higher pitches to be ordered lower

Suggestion: Put correct range order in range.js
    C0,C#0,D0,D#0,E0,F0,F#0,G0,G#0,A0,A#0,B0,C1,...

This should fix...
    Bug where notes outside of the range is playing
    Some crashes when certain ranges were selected

**Comment by hectarek** [comment]
I don't think this issue is present anymore. Closing this out.
