### ISSUE TITLE
Tempo doesnt line up with real world tempos

### ISSUE THREAD

**Issue by rcarm98** [hectarek/Random-pitch-generator#5]
Tempos are usually off by 1 bpm or sometimes by 2 bpm.  The preset of 120 seems to work correctly but all other tempos are off by 1 (or 2) bpm up or 1 (or 2) bpm down.  There seems to be no detectable pattern for which will be 1 (or 2) higher and which will be 1 (or 2) lower and sometimes if you refresh the page, one tempo will change direction from 1 (or 2) bpm higher to 1 (or 2) bpm lower.  Honestly I got no theories for whats goin on.  Best of luck and let me know if theres any way to help.

**Comment by hectarek** [comment]
After out meeting this past wednesday (the meeting on Wednesday, Wednesday's meeting) this is really only noticable on really low tempos. As such, the minimum tempo will now be 40 bpm.
