### ISSUE TITLE
Metronome desyncs with play

### ISSUE THREAD

**Issue by HouseOfBLus** [hectarek/Random-pitch-generator#6]
After a while, the metronome will desync from the play. This occurs at all tempos.

**Comment by hectarek** [comment]
Talked with Robert, the issue might just be because of how slow the app is syncing up, probably not huge issue for the mobile implementation.

**Comment by hectarek** [comment]
Will temporarily use a delay on play in order to give the app time to load before. Might not fix every instance of this but will at least help some.
